### ISSUE TITLE
ImGui Bindings?

### ISSUE THREAD

**Issue by sodomon2** [stetre/moonlibs#6]
Hello,
I was wondering if you were thinking of making a bindings for [ImGui](https://github.com/ocornut/imgui)

Thank You!

**Comment by stetre** [comment]
Hi. I've actually considered it in the past, when I wrote the bindings for Nuklear. I chose the latter because it's C (C++ gives me headaches...). I may reconsider the option in the future, who knows, but right know I have plenty of other things in my backlog of things I would like to do, so don't count on it.

(I may assist anyone who would give it a try, however.)

**Comment by sodomon2** [comment]
OH! ok, then I will close this :)
